export enum DOT_ENV {
  //APP
  APP_URL = 'APP_URL',
  APP_PORT = 'APP_PORT',
  //DB 
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  //s3
  S3_ACCSESS_KEY = 'S3_ACCSESS_KEY',
  S3_SECRET_KEY = 'S3_SECRET_KEY',
  S3_ENDPOINT = 'S3_ENDPOINT',
  S3_BUCKET_NAME = 'S3_BUCKET_NAME'
}